/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MentalHealthAssessmentService } from "../mentalHealthAssessment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MentalHealthAssessmentCreateInput } from "./MentalHealthAssessmentCreateInput";
import { MentalHealthAssessment } from "./MentalHealthAssessment";
import { MentalHealthAssessmentFindManyArgs } from "./MentalHealthAssessmentFindManyArgs";
import { MentalHealthAssessmentWhereUniqueInput } from "./MentalHealthAssessmentWhereUniqueInput";
import { MentalHealthAssessmentUpdateInput } from "./MentalHealthAssessmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MentalHealthAssessmentControllerBase {
  constructor(
    protected readonly service: MentalHealthAssessmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MentalHealthAssessment })
  @nestAccessControl.UseRoles({
    resource: "MentalHealthAssessment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMentalHealthAssessment(
    @common.Body() data: MentalHealthAssessmentCreateInput
  ): Promise<MentalHealthAssessment> {
    return await this.service.createMentalHealthAssessment({
      data: {
        ...data,

        userProfile: data.userProfile
          ? {
              connect: data.userProfile,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,
        date: true,
        details: true,
        typeField: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MentalHealthAssessment] })
  @ApiNestedQuery(MentalHealthAssessmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MentalHealthAssessment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mentalHealthAssessments(
    @common.Req() request: Request
  ): Promise<MentalHealthAssessment[]> {
    const args = plainToClass(
      MentalHealthAssessmentFindManyArgs,
      request.query
    );
    return this.service.mentalHealthAssessments({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,
        date: true,
        details: true,
        typeField: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MentalHealthAssessment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MentalHealthAssessment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mentalHealthAssessment(
    @common.Param() params: MentalHealthAssessmentWhereUniqueInput
  ): Promise<MentalHealthAssessment | null> {
    const result = await this.service.mentalHealthAssessment({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,
        date: true,
        details: true,
        typeField: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MentalHealthAssessment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MentalHealthAssessment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMentalHealthAssessment(
    @common.Param() params: MentalHealthAssessmentWhereUniqueInput,
    @common.Body() data: MentalHealthAssessmentUpdateInput
  ): Promise<MentalHealthAssessment | null> {
    try {
      return await this.service.updateMentalHealthAssessment({
        where: params,
        data: {
          ...data,

          userProfile: data.userProfile
            ? {
                connect: data.userProfile,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          score: true,
          date: true,
          details: true,
          typeField: true,

          userProfile: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MentalHealthAssessment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MentalHealthAssessment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMentalHealthAssessment(
    @common.Param() params: MentalHealthAssessmentWhereUniqueInput
  ): Promise<MentalHealthAssessment | null> {
    try {
      return await this.service.deleteMentalHealthAssessment({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          score: true,
          date: true,
          details: true,
          typeField: true,

          userProfile: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
