/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  MentalHealthAssessment as PrismaMentalHealthAssessment,
  UserProfile as PrismaUserProfile,
} from "@prisma/client";

export class MentalHealthAssessmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MentalHealthAssessmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.mentalHealthAssessment.count(args);
  }

  async mentalHealthAssessments(
    args: Prisma.MentalHealthAssessmentFindManyArgs
  ): Promise<PrismaMentalHealthAssessment[]> {
    return this.prisma.mentalHealthAssessment.findMany(args);
  }
  async mentalHealthAssessment(
    args: Prisma.MentalHealthAssessmentFindUniqueArgs
  ): Promise<PrismaMentalHealthAssessment | null> {
    return this.prisma.mentalHealthAssessment.findUnique(args);
  }
  async createMentalHealthAssessment(
    args: Prisma.MentalHealthAssessmentCreateArgs
  ): Promise<PrismaMentalHealthAssessment> {
    return this.prisma.mentalHealthAssessment.create(args);
  }
  async updateMentalHealthAssessment(
    args: Prisma.MentalHealthAssessmentUpdateArgs
  ): Promise<PrismaMentalHealthAssessment> {
    return this.prisma.mentalHealthAssessment.update(args);
  }
  async deleteMentalHealthAssessment(
    args: Prisma.MentalHealthAssessmentDeleteArgs
  ): Promise<PrismaMentalHealthAssessment> {
    return this.prisma.mentalHealthAssessment.delete(args);
  }

  async getUserProfile(parentId: string): Promise<PrismaUserProfile | null> {
    return this.prisma.mentalHealthAssessment
      .findUnique({
        where: { id: parentId },
      })
      .userProfile();
  }
}
